[package]
name = "panic"
version = "0.1.0"
edition = "2021"

# Abort on panic in release mode.
[profile.release]
panic = 'abort'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
